import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AdminSidebar from "@/app/components/SideBar";
import Footer from "@/app/components/Footer";
import Providers from "@/app/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AdminSidebar />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
